version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing source dependencies...
      - pip install -r mysite/lambda_function_for_def_generate_image/requirements.txt -t /tmp/dependencies
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd mysite/lambda_function_for_def_generate_image
      - zip -r9 /tmp/function.zip lambda_function.py  # Only include the lambda_function.py in the zip
      - cd /tmp/dependencies
      - zip -ur /tmp/function.zip .  # Add the contents of the dependencies directory to the zip
  post_build:
    commands:
      - echo Build completed on `date`
      - timestamp=$(date +%Y%m%d%H%M%S)
      - sed -i "s/<PLACEHOLDER_FOR_TIMESTAMP>/$timestamp/" $CODEBUILD_SRC_DIR/mysite/lambda_function_for_def_generate_image/deploy.yaml
      - aws s3 cp /tmp/function.zip s3://draft-lambda-functions/generate_image/function.zip
      - aws cloudformation deploy --stack-name imagegenerate --template-file $CODEBUILD_SRC_DIR/mysite/lambda_function_for_def_generate_image/deploy.yaml --capabilities CAPABILITY_IAM
artifacts:
  files:
    - /tmp/function.zip
    - mysite/lambda_function_for_def_generate_image/deploy.yaml

cache:
  paths:
    - '/root/.cache/pip/**/*'
