version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing source dependencies...
      - pip install -r mysite/lambda_function_for_def_generate_image/requirements.txt -t /tmp/dependencies
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Listing contents of the root directory...
      - ls -la
      - echo Listing contents of the codebuild source directory...
      - ls -la $CODEBUILD_SRC_DIR
      - echo Building the Lambda function package...
      - cd $CODEBUILD_SRC_DIR/mysite/lambda_function_for_def_generate_image
      - zip -r9 /tmp/function.zip lambda_function.py  # Only include the lambda_function.py in the zip
      - echo Adding dependencies to the lambda function package...
      - cd /tmp/dependencies
      - zip -ur /tmp/function.zip .  # Add only the dependencies to the zip
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Updating timestamp in deploy.yaml...
      - timestamp=$(date +%Y%m%d%H%M%S)
      - sed -i "s/UNIQUE_ID_PLACEHOLDER/$timestamp/" $CODEBUILD_SRC_DIR/mysite/lambda_function_for_def_generate_image/deploy.yaml
      - echo Copying function.zip to the root directory of the build...
      - cp /tmp/function.zip $CODEBUILD_SRC_DIR/function.zip
      - echo Uploading the Lambda function package to S3...
      - aws s3 cp $CODEBUILD_SRC_DIR/function.zip s3://draft-lambda-functions/generate_image/function.zip

artifacts:
  files:
    - mysite/lambda_function_for_def_generate_image/lambda_function.py
    - mysite/lambda_function_for_def_generate_image/deploy.yaml
    - function.zip
  discard-paths: no

cache:
  paths:
    - '/root/.cache/pip/**/*'
