version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10  # Adjust the Python version as needed
    commands:
      - echo Installing source dependencies...
      - pip install --upgrade pip
      - pip install requests  # Example dependency

  build:
    commands:
      - echo Build started on `date`
      - echo "Creating a test file for upload..."
      - echo "This is a test file." > testfile.txt

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading the test file...
      - aws s3 cp testfile.txt s3://codepipeline-us-east-1-72537565188/testfile.txt
