version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10  # Adjust Python version if necessary. Python 10 may not be valid.
    commands:
      - echo Installing source dependencies...
      - pip install -r draftmerch/mysite/lambda_function_for_def_generate_image/requirements.txt -t /tmp/dependencies

  pre_build:
    commands:
      - echo Pre-build phase...

  build:
    commands:
      - echo Build started on `date`
      - cd draftmerch/mysite/lambda_function_for_def_generate_image
      - zip -r /tmp/function.zip handler.py
      - cd /tmp/dependencies
      - zip -ur /tmp/function.zip .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading the build artifacts...
      - aws s3 cp /tmp/function.zip s3://codepipeline-us-east-1-72537565188/lambda_function_for_/BuildArtif/function.zip

cache:
  paths:
    - '/root/.cache/pip/**/*'
