AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS CloudFormation template to deploy Lambda function.

Parameters:
  FunctionCodeS3Version:
    Type: String
    Default: ""
    Description: S3 object version of the Lambda code package

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: gen_ima
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: draft-lambda-functions
        S3Key: generate_image/function.zip
        S3ObjectVersion: !Ref FunctionCodeS3Version
      Runtime: python3.10
      Timeout: 60
      MemorySize: 128
      Description: "Generates initial image"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:*'
                Resource: 'arn:aws:logs:*:*:*'
