version: 0.2

phases:
  build:
    commands:
      - echo "Syncing specific directories to S3..."
  post_build:
    commands:
      - aws s3 sync mysite/templates s3://static-merchdraft/templates --delete
      - aws s3 sync mysite/static/script s3://static-merchdraft/static/script --delete
      - aws s3 sync mysite/static/css s3://static-merchdraft/static/css --delete
