AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to deploy Lambda function for route_generate_image.

Parameters:
  LambdaFunctionDescription:
    Type: String
    Default: "Generates route for image - Deployment ID: UNIQUE_ID_PLACEHOLDER"
  FunctionCodeS3ObjectVersion:
    Type: String
    Default: "VERSION_ID_PLACEHOLDER"

Resources:
  GenLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: gen
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: draft-lambda-functions
        S3Key: generate/function.zip
        S3ObjectVersion: !Ref FunctionCodeS3ObjectVersion
      Runtime: python3.10
      Timeout: 120
      MemorySize: 256
      Description: !Ref LambdaFunctionDescription

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:*'
                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource: 'arn:aws:lambda:us-east-1:905418180959:function:gen_ima'  # Specify the ARN of Lambda functions that this function invokes

Outputs:
  GenLambdaFunctionArn:
    Description: ARN of the gen function
    Value: !GetAtt GenLambdaFunction.Arn
