version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y python3 python3-pip gcc cairo-devel pango-devel gdk-pixbuf2-devel zip
      - pip3 install --upgrade pip

  pre_build:
    commands:
      - pip3 install cairosvg -t /cairosvg_layer/python/lib/python3.10/site-packages/

  build:
    commands:
      - mkdir -p /opt/python/lib/python3.10/site-packages/
      - mkdir -p /opt/lib
      - cp -r /cairosvg_layer/python/lib/python3.10/site-packages/* /opt/python/lib/python3.10/site-packages/
      - cp /usr/lib64/libcairo.so.2 /opt/lib/
      - cp /usr/lib64/libpango-1.0.so.0 /opt/lib/
      - cp /usr/lib64/libpangocairo-1.0.so.0 /opt/lib/
      - cp /usr/lib64/libgdk_pixbuf-2.0.so.0 /opt/lib/
      # Search for libpng16.so.16 across the entire filesystem and copy it if found
      - find / -name libpng16.so.16 -exec cp {} /opt/lib/ \; -quit
      - cd /opt
      - zip -r /cairosvg_layer.zip .
      - mv /cairosvg_layer.zip /cairosvg_layer.zip

  post_build:
    commands:
      - echo "Uploading the Lambda layer zip to S3..."
      - aws s3 cp /cairosvg_layer.zip s3://draft-lambda-layers/cairosvg/

artifacts:
  files:
    - /cairosvg_layer.zip
