version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y python3 python3-pip gcc cairo-devel pango-devel gdk-pixbuf2-devel zip
      - pip3 install --upgrade pip

  pre_build:
    commands:
      - pip3 install cairosvg -t /opt/python/lib/python3.10/site-packages/

  build:
    commands:
      - mkdir -p /opt/lib
      - cp /usr/lib64/libcairo.so.2 /opt/lib/
      - cp /usr/lib64/libpango-1.0.so.0 /opt/lib/
      - cp /usr/lib64/libpangocairo-1.0.so.0 /opt/lib/
      - cp /usr/lib64/libgdk_pixbuf-2.0.so.0 /opt/lib/
      # Ensure libpng16.so.16 is found and copied to /opt/lib
      - find / -name libpng16.so.16 -exec cp {} /opt/lib/ \; -quit
      # Use ldd to check dependencies (for manual inspection)
      - ldd /opt/lib/libcairo.so.2
      - ldd /opt/lib/libpango-1.0.so.0
      - ldd /opt/lib/libpangocairo-1.0.so.0
      - ldd /opt/lib/libgdk_pixbuf-2.0.so.0
      # Prepare the rest of the layer
      - chmod -R 755 /opt
      - cd /
      - zip -r /cairosvg_layer.zip opt

  post_build:
    commands:
      - echo "Uploading the Lambda layer zip to S3..."
      - aws s3 cp /cairosvg_layer.zip s3://draft-lambda-layers/cairosvg/
