version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y python3 python3-pip gcc cairo-devel pango-devel gdk-pixbuf2-devel zip
      - pip3 install --upgrade pip

  pre_build:
    commands:
      - pip3 install cairosvg -t /python/lib/python3.10/site-packages/

  build:
    commands:
      - mkdir -p /lib
      # Copy primary libraries
      - cp /usr/lib64/libcairo.so.2 /lib/
      - cp /usr/lib64/libpango-1.0.so.0 /lib/
      - cp /usr/lib64/libpangocairo-1.0.so.0 /lib/
      - cp /usr/lib64/libgdk_pixbuf-2.0.so.0 /lib/
      # Find libpng16.so.16 and copy it along with its dependencies
      - find / -name libpng16.so.16 -exec cp {} /lib/ \;
      - ldd /lib/libpng16.so.16 | tr -s '[:space:]' '\n' | grep '^/' | xargs -I {} cp {} /lib/
      # Use ldd to find dependencies of the copied libraries and copy them as well
      - ldd /lib/libcairo.so.2 | tr -s '[:space:]' '\n' | grep '^/' | xargs -I {} cp {} /lib/
      - ldd /lib/libpango-1.0.so.0 | tr -s '[:space:]' '\n' | grep '^/' | xargs -I {} cp {} /lib/
      - ldd /lib/libpangocairo-1.0.so.0 | tr -s '[:space:]' '\n' | grep '^/' | xargs -I {} cp {} /lib/
      - ldd /lib/libgdk_pixbuf-2.0.so.0 | tr -s '[:space:]' '\n' | grep '^/' | xargs -I {} cp {} /lib/
      # Prepare for the ZIP creation
      - chmod -R 755 /lib /python
      - cd /
      - zip -r /cairosvg_layer.zip lib python

  post_build:
    commands:
      - echo "Uploading the Lambda layer zip to S3..."
      - aws s3 cp /cairosvg_layer.zip s3://draft-lambda-layers/cairosvg/
